//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _piris.DomainService.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_positions
    {
        public sbyte id { get; set; }
        public int Id { get; internal set; }
        public string positionName { get; set; }
        public string positionType { get; set; }
        public int positionValue { get; set; }
        public int positionPrice { get; set; }
        public string positionCurrency { get; set; }
        public int priceCurrency { get; set; }
    }
}
