//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _piris.DomainService.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_users
    {
        public sbyte id { get; set; }
        public string userName { get; set; }
        public string userPassword { get; set; }
    }
}
